on:
  push:

jobs:
  pack:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          get-location
          get-childitem
        working-directory: setup
        shell: pwsh
